name: GodCraft
version: 2.0
description: Become the god of your server!

authors: [DiamondIceNS, TheHarrisonCrafter]
website: https://github.com/DiamondIceNS/God-Craft

main: co.orre.godcraft.God

commands:
  boom:
    description: Creates an explosion around a player.
    usage: /boom <username> [power]
  burn:
    description: Sets a player on fire.
    usage: /burn <username>
  feed:
    description: Sets a players food bar to max.
    usage: /feed [username]
  getcrafting:
    description: Shows a crafting window.
    usage: /getcrafting
  getenchanting:
    description: Shows an enchanting window.
    usage: /getenchanting
  getenderchest:
    description: Shows a players enderchest.
    usage: /getenderchest <username>
  getinventory:
    description: Shows a players inventory.
    usage: /getinventory <username>
  heal:
    description: Gives player full health.
    usage: /heal <username>
  lightning:
    description: Shoots a bolt of lightning on the block that the players croshair is pointing at. Set 1 to make the bolt deal damage and set things on fire.
    usage: /lightning [0|1]
  murder:
    description: Kills a player without warning.
    usage: /murder <username>
  nickname:
    description: Change players chat and list name.
    usage: /nickname [username] <newname>
    aliases: nick
  ping:
    description: This is a Ping utility.
    usage: /ping
  setfoodlevel:
    description: Set the foodbar level for a player.
    usage: /setfoodlevel <username> <level>
  sethealth:
    description: Set the health for a player.
    usage: /sethealth <username> <health>
  setlevel:
    description: Set the level for a player.
    usage: /setlevel <username> <level>
  setmaxair:
    description: Set the maximum air for a player.
    usage: /setmaxair <username> [airleval]
  setmaxhealth:
    description: Set the maximum health for a player.
    usage: /setmaxhealth <username> [healthleval]
  starve:
    description: Set a players food bar to zero.
    usage: /starve [username]
  throw:
    description: Make a player throw a snowball, egg, or arrow.
    usage: /throw [username] <egg|snowball|arrow>
  troll:
    description: Troll a player.
    usage: /troll <username>

permissions:
    godcraft.*:
      description: Gives all God Craft command permissions.
      children:
        godcraft.boom: true
        godcraft.burn: true
        godcraft.feed: true
        godcraft.get_crafting: true
        godcraft.get_enchanting: true
        godcraft.getEnderChest: true
        godcraft.getInventory: true
        godcraft.heal: true
        godcraft.lighting: true
        godcraft.murder: true
        godcraft.nickname: true
        godcraft.ping: true
        godcraft.set_food_level: true
        godcraft.set_health: true
        godcraft.set_level: true
        godcraft.set_max_air: true
        godcraft.set_max_health: true
        godcraft.starve: true
        godcraft.throw: true
        godcraft.troll: true
    godcraft.Bboom:
      description: Allows user to use boom command.
      default: op
    godcraft.burn:
      description: Allows user to use burn command.
      default: op
    godcraft.feed:
      description: Allows user to use feed command.
      default: op
    godcraft.get_crafting:
      description: Allows user to use getcrafting command.
      default: op
    godcraft.get_enchanting:
      description: Allows user to use getenchanting command.
      default: op
    godcraft.get_ender_chest:
      description: Allows user to use getenderchest command.
      default: op
    godcraft.get_inventory:
      description: Allows user to use getinventory command.
      default: op
    godcraft.heal:
      description: Allows user to use heal command.
      default: op
    godcraft.lightning:
      description: Allows user to use lightning command.
      default: op
    godcraft.murder:
      description: Allows user to use murder command.
      default: op
    godcraft.nickname:
      description: Allows user to use nickname or nick command.
      default: op
    godcraft.ping:
      description: Allows user to use ping command.
      default: true
    godcraft.set_food_level:
      description: Allows user to use setfoodlevel command.
      default: op
    godcraft.set_health:
      description: Allows user to use sethealth command.
      default: op
    godcraft.set_level:
      description: Allows user to use setlevel command.
      default: op
    godcraft.set_max_air:
      description: Allows user to use setmaxair command.
      default: op
    godcraft.set_max_health:
      description: Allows user to use setmaxair command.
      default: op
    godcraft.starve:
      Description: Allows user to use starve command.
      default: op
    godcraft.throw:
      description: Allows user to use throw command.
      default: op
    godcraft.troll:
      description: Allows user to use the troll command.
      default: op