name: GoddessCraft
version: '@VERSION@'
description: '@DESCRIPTION@'

authors: [DiamondIceNS, TheHarrisonCrafter]
website: '@URL@'

main: co.orre.goddesscraft.Goddess

commands:
  boom:
    description: Creates an explosion around a player.
    usage: /boom <username> [power]
  burn:
    description: Sets a player on fire.
    usage: /burn <username>
  feed:
    description: Sets a players food bar to max.
    usage: /feed [username]
  getcrafting:
    description: Shows a crafting window.
    usage: /getcrafting
  getenchanting:
    description: Shows an enchanting window.
    usage: /getenchanting
  getenderchest:
    description: Shows a players enderchest.
    usage: /getenderchest <username>
  getinventory:
    description: Shows a players inventory.
    usage: /getinventory <username>
  goddesscraft:
    description: Used to make changes to the plugin
    usage: /goddesscraft [reload|debug] <args>
    alias: gc
  heal:
    description: Gives player full health.
    usage: /heal <username>
  lightning:
    description: Shoots a bolt of lightning on the block that the players croshair is pointing at. Set 1 to make the bolt deal damage and set things on fire.
    usage: /lightning [0|1]
  murder:
    description: Kills a player without warning.
    usage: /murder <username>
  nickname:
    description: Change players chat and list name.
    usage: /nickname [username] <newname>
    aliases: nick
  ping:
    description: This is a Ping utility.
    usage: /ping
  setfoodlevel:
    description: Set the foodbar level for a player.
    usage: /setfoodlevel <username> <level>
  sethealth:
    description: Set the health for a player.
    usage: /sethealth <username> <health>
  setlevel:
    description: Set the level for a player.
    usage: /setlevel <username> <level>
  setmaxair:
    description: Set the maximum air for a player.
    usage: /setmaxair <username> [airleval]
  setmaxhealth:
    description: Set the maximum health for a player.
    usage: /setmaxhealth <username> [healthleval]
  starve:
    description: Set a players food bar to zero.
    usage: /starve [username]
  throw:
    description: Make a player throw a snowball, egg, or arrow.
    usage: /throw [username] <egg|snowball|arrow>
  troll:
    description: Troll a player.
    usage: /troll <username>

permissions:
    goddesscraft.*:
      description: Gives all Goddess Craft command permissions.
      children:
        goddesscraft.boom: true
        goddesscraft.burn: true
        goddesscraft.feed: true
        goddesscraft.get_crafting: true
        goddesscraft.get_enchanting: true
        goddesscraft.get_ender_chest: true
        goddesscraft.get_inventory: true
        goddesscraft.goddess_craft: true
        goddesscraft.heal: true
        goddesscraft.lighting: true
        goddesscraft.murder: true
        goddesscraft.nickname: true
        goddesscraft.ping: true
        goddesscraft.set_food_level: true
        goddesscraft.set_health: true
        goddesscraft.set_level: true
        goddesscraft.set_max_air: true
        goddesscraft.set_max_health: true
        goddesscraft.starve: true
        goddesscraft.throw: true
        goddesscraft.troll: true
    goddesscraft.boom:
      description: Allows user to use boom command.
      default: op
    goddesscraft.burn:
      description: Allows user to use burn command.
      default: op
    goddesscraft.feed:
      description: Allows user to use feed command.
      default: op
    goddesscraft.get_crafting:
      description: Allows user to use getcrafting command.
      default: op
    goddesscraft.get_enchanting:
      description: Allows user to use getenchanting command.
      default: op
    goddesscraft.get_ender_chest:
      description: Allows user to use getenderchest command.
      default: op
    goddesscraft.get_inventory:
      description: Allows user to use getinventory command.
      default: op
    goddesscraft.goddess_craft:
          description: Allows user to use goddesscraft command.
          default: op
    goddesscraft.heal:
      description: Allows user to use heal command.
      default: op
    goddesscraft.lightning:
      description: Allows user to use lightning command.
      default: op
    goddesscraft.murder:
      description: Allows user to use murder command.
      default: op
    goddesscraft.nickname:
      description: Allows user to use nickname or nick command.
      default: op
    goddesscraft.ping:
      description: Allows user to use ping command.
      default: true
    goddesscraft.set_food_level:
      description: Allows user to use setfoodlevel command.
      default: op
    goddesscraft.set_health:
      description: Allows user to use sethealth command.
      default: op
    goddesscraft.set_level:
      description: Allows user to use setlevel command.
      default: op
    goddesscraft.set_max_air:
      description: Allows user to use setmaxair command.
      default: op
    goddesscraft.set_max_health:
      description: Allows user to use setmaxair command.
      default: op
    goddesscraft.starve:
      Description: Allows user to use starve command.
      default: op
    goddesscraft.throw:
      description: Allows user to use throw command.
      default: op
    goddesscraft.troll:
      description: Allows user to use the troll command.
      default: op